name: Build site

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: jakejarvis/hugo-build-action@v0.108.0
      - uses: actions/upload-artifact@v3
        with:
          name: website
          path: './public'